version: '3.1'

services:
    couchbase-server:
        image: couchbase/server:community
        volumes:
          - couchbase_data:/opt/couchbase/var
        ports:
          - 8091-8094:8091-8094
          - 11210:11210
volumes:
  couchbase_data:
        external: true
