INSERT INTO `soava-dia` ( KEY, VALUE )
  VALUES("tanaAnalakely", { "docType": "location", "name": "Analakely" }),
  VALUES("tanaAmbatomaro", { "docType": "location", "name": "Ambatomaro" }),
  VALUES("tanaVatosoa", { "docType": "location", "name": "Vatosoa"}),
  VALUES("tanaTanyMalalaka", { "docType": "location", "name": "TanyMalalaka"}),
  VALUES("tanaBesarety", { "docType": "location", "name": "Besarety"}),
  VALUES("tanaRasalama", { "docType": "location", "name": "Rasalama"}),
  VALUES("tanaBelAir", { "docType": "location", "name": "BelAir"}),
  VALUES("tanaTotal", { "docType": "location", "name": "Total"}),
  VALUES("tanaFivondranana", { "docType": "location", "name": "Fivondranana" }),
  VALUES("tanaAnkadivatoMascott", { "docType": "location", "name": "AnkadivatoMascottFitsema"}),
  VALUES("tanaAmbohijatovo", { "docType": "location", "name": "Ambohijatovo"}),
  VALUES("tanaMahamasina", { "docType": "location", "name": "Mahamasina"}),
  VALUES("tanaAnosy", { "docType": "location", "name": "Anosy"}),
   VALUES("fitsema", { "docType": "cooperative", "name": "Fitsema", "telephone": "0341723781" }),
     VALUES( "sprinter", { "docType": "vehicleModel", "name": "Mercedes Benz Sprinter" }),
    VALUES( "vehicle147", { "docType": "vehicle", "name": "147", "vehicleModelId": "sprinter", "cooperativeId": "fitsema" }),
    VALUES( "route114a", { "docType": "route", "name": "A", "vehicleId": "vehicle114"}),
    VALUES( "route147a", { "docType": "route", "name": "A", "vehicleId": "vehicle147", 
        "serviceStationLocations": ["tanaAmbatomaro"],
        "onReturnLocations": ["mahamasina"],
        "locations": ["tanaAmbatomaro", "tanaVatosoa", 
                "tanaTanyMalalaka", "tanaBesarety", "tanaRasalama",
                "tanaBelAir", "tanaTotal", "tanaFivondranana", "tanaAnkadivatoMascott",
                "tanaAmbohijatovo", "tanaMahamasina", "tanaAnosy"]
    })
